#!/usr/bin/env python3
"""生成 Biopolitics Phase 2 golden fixture，供 Rust 逐字段 parity 比对。

运行 Python build_note_regions + build_note_items，序列化输出到
`fnm_re_rs/fnm-phase2/tests/fixtures/biopolitics_phase2_golden.json`。

用法:
    PYTHONPATH=. python tools/gen_biopolitics_phase2_golden.py

输出结构:
    {
      "total_pages": 370,
      "note_regions": [...],
      "note_items": [...]
    }
"""

from __future__ import annotations

import json, sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

FIXTURES_DIR = REPO_ROOT / "fnm_re_rs" / "fnm-phase2" / "tests" / "fixtures"
BIOPOLITICS_RAW = REPO_ROOT / "test_example" / "Biopolitics" / "raw_pages.json"

BIOPOLITICS_TOC = [
    ("Leçon du 10 janvier 1979", 17),
    ("Leçon du 17 janvier 1979", 43),
    ("Leçon du 24 janvier 1979", 67),
    ("Leçon du 31 janvier 1979", 90),
    ("Leçon du 7 février 1979", 107),
    ("Leçon du 14 février 1979", 130),
    ("Leçon du 21 février 1979", 149),
    ("Leçon du 28 février 1979", 165),
    ("Leçon du 7 mars 1979", 192),
    ("Leçon du 14 mars 1979", 219),
    ("Leçon du 21 mars 1979", 252),
    ("Leçon du 4 avril 1979", 290),
]
TOTAL_PAGES = 370


def load_pages() -> list[dict]:
    data = json.loads(BIOPOLITICS_RAW.read_text(encoding="utf-8"))
    pages = data.get("pages", []) if isinstance(data, dict) else data
    assert len(pages) == TOTAL_PAGES
    return pages


def build_toc_items() -> list[dict]:
    items: list[dict] = []
    for i, (title, start_page) in enumerate(BIOPOLITICS_TOC):
        end_page = BIOPOLITICS_TOC[i + 1][1] - 1 if i + 1 < len(BIOPOLITICS_TOC) else TOTAL_PAGES
        items.append({
            "item_id": f"toc-ch-{i + 1}",
            "title": title,
            "target_pdf_page": start_page,
            "end_page": end_page,
            "role_hint": "chapter",
            "level": 1,
            "parent_id": None,
        })
    return items


def _record_to_dict(record: Any) -> dict:
    if hasattr(record, "__dataclass_fields__"):
        result: dict = {}
        for f in record.__dataclass_fields__:
            val = getattr(record, f)
            result[f] = _serialize_value(val)
        return result
    if isinstance(record, dict):
        return {k: _serialize_value(v) for k, v in record.items()}
    return {"_raw": str(record)}


def _serialize_value(val: Any) -> Any:
    if val is None:
        return None
    if isinstance(val, (bool, int, float, str)):
        return val
    if isinstance(val, (list, tuple)):
        return [_serialize_value(v) for v in val]
    if isinstance(val, dict):
        return {str(k): _serialize_value(v) for k, v in val.items()}
    if hasattr(val, "__dataclass_fields__"):
        return _record_to_dict(val)
    return str(val)


def main() -> None:
    from FNM_RE.app.pipeline import build_phase1_structure, build_phase2_structure

    pages = load_pages()
    toc_items = build_toc_items()

    # Phase 1
    print("Running Phase 1 ...")
    phase1 = build_phase1_structure(pages, toc_items=toc_items, toc_offset=0)

    # Phase 2
    print("Running Phase 2 ...")
    phase2 = build_phase2_structure(pages, toc_items=toc_items, toc_offset=0)

    golden = {
        "_comment": "Biopolitics Phase 2 golden — generated by tools/gen_biopolitics_phase2_golden.py",
        "_generated_from": "Python FNM_RE pipeline",
        "total_pages": len(pages),
        "note_regions": [_record_to_dict(r) for r in phase2.note_regions],
        "note_items": [_record_to_dict(r) for r in phase2.note_items],
    }

    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    out = FIXTURES_DIR / "biopolitics_phase2_golden.json"
    out.write_text(json.dumps(golden, ensure_ascii=False, indent=2))
    print(f"\nGolden written to {out}")
    print(f"  note_regions:  {len(golden['note_regions'])}")
    print(f"  note_items:    {len(golden['note_items'])}")


if __name__ == "__main__":
    main()
