#!/usr/bin/env python3
"""生成 Biopolitics Phase 1 golden fixture，供 Rust 逐字段 parity 比对。

运行 Python `build_page_partitions` + `build_chapter_skeleton`，序列化全部输出到
`fnm_re_rs/fnm-phase1/tests/fixtures/biopolitics_phase1_golden.json`。

用法:
    PYTHONPATH=. python tools/gen_biopolitics_golden.py
    PYTHONPATH=. python tools/gen_biopolitics_golden.py --pdf /path/to/Biopolitics.pdf  # 含 pdf_font_band

输出结构:
    {
      "total_pages": 370,
      "page_partitions": [...],
      "chapters": [...],
      "heading_candidates": [...],
      "post_body_titles": [...],
      "toc_role_summary": {...}
    }
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

FIXTURES_DIR = REPO_ROOT / "fnm_re_rs" / "fnm-phase1" / "tests" / "fixtures"
BIOPOLITICS_RAW = REPO_ROOT / "test_example" / "Biopolitics" / "raw_pages.json"

# Biopolitics 硬编码 TOC（与 Rust test_biopolitics_parity.rs 一致）
BIOPOLITICS_TOC = [
    ("Leçon du 10 janvier 1979", 17),
    ("Leçon du 17 janvier 1979", 43),
    ("Leçon du 24 janvier 1979", 67),
    ("Leçon du 31 janvier 1979", 90),
    ("Leçon du 7 février 1979", 107),
    ("Leçon du 14 février 1979", 130),
    ("Leçon du 21 février 1979", 149),
    ("Leçon du 28 février 1979", 165),
    ("Leçon du 7 mars 1979", 192),
    ("Leçon du 14 mars 1979", 219),
    ("Leçon du 21 mars 1979", 252),
    ("Leçon du 4 avril 1979", 290),
]
TOTAL_PAGES = 370


def load_pages() -> list[dict]:
    data = json.loads(BIOPOLITICS_RAW.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        pages = data.get("pages", [])
    else:
        pages = data
    assert len(pages) == TOTAL_PAGES, f"Expected {TOTAL_PAGES} pages, got {len(pages)}"
    return pages


def build_toc_items() -> list[dict]:
    """构建与 Rust test 一致的 TOC items。"""
    items: list[dict] = []
    for i, (title, start_page) in enumerate(BIOPOLITICS_TOC):
        end_page = (
            BIOPOLITICS_TOC[i + 1][1] - 1
            if i + 1 < len(BIOPOLITICS_TOC)
            else TOTAL_PAGES
        )
        items.append({
            "item_id": f"toc-ch-{i + 1}",
            "title": title,
            "target_pdf_page": start_page,
            "end_page": end_page,
            "role_hint": "chapter",
            "level": 1,
            "parent_id": None,
        })
    return items


def _record_to_dict(record: Any) -> dict:
    """将 dataclass/simple-namespace 记录转为普通 dict。"""
    if hasattr(record, "__dataclass_fields__"):
        result: dict = {}
        for f in record.__dataclass_fields__:
            val = getattr(record, f)
            result[f] = _serialize_value(val)
        return result
    if isinstance(record, dict):
        return {k: _serialize_value(v) for k, v in record.items()}
    return {"_raw": str(record)}


def _serialize_value(val: Any) -> Any:
    if val is None:
        return None
    if isinstance(val, (bool, int, float, str)):
        return val
    if isinstance(val, (list, tuple)):
        return [_serialize_value(v) for v in val]
    if isinstance(val, dict):
        return {str(k): _serialize_value(v) for k, v in val.items()}
    if hasattr(val, "__dataclass_fields__"):
        return _record_to_dict(val)
    return str(val)


def main(pdf_path: str = "") -> None:
    from FNM_RE.stages.page_partition import build_page_partitions
    from FNM_RE.stages.chapter_skeleton.builder import build_chapter_skeleton

    pages = load_pages()
    toc_items = build_toc_items()

    # Phase 1a: page_partition
    print("Running build_page_partitions ...")
    partitions, pre_extracted_candidates, file_idx_map = build_page_partitions(pages)

    # Phase 1b: chapter_skeleton
    print(f"Running build_chapter_skeleton (pdf_path={pdf_path or '(none)'}) ...")
    heading_candidates, chapters, meta = build_chapter_skeleton(
        partitions,
        toc_items=toc_items,
        toc_offset=0,
        pdf_path=pdf_path,
        pages=pages,
        pre_extracted_page_candidates=pre_extracted_candidates,
        file_idx_map=file_idx_map,
    )

    # 组装 golden
    golden = {
        "_comment": "Biopolitics Phase 1 golden — generated by tools/gen_biopolitics_golden.py",
        "_generated_from": "Python FNM_RE pipeline",
        "total_pages": len(pages),
        "page_partitions": [_record_to_dict(r) for r in partitions],
        "chapters": [_record_to_dict(r) for r in chapters],
        "heading_candidates": [_record_to_dict(r) for r in heading_candidates],
        "post_body_titles": _serialize_value(meta.get("post_body_titles", [])),
        "toc_role_summary": _serialize_value(meta.get("toc_role_summary", {})),
    }

    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    out = FIXTURES_DIR / "biopolitics_phase1_golden.json"
    out.write_text(json.dumps(golden, ensure_ascii=False, indent=2))
    print(f"\nGolden written to {out}")
    print(f"  page_partitions:     {len(golden['page_partitions'])}")
    print(f"  chapters:            {len(golden['chapters'])}")
    print(f"  heading_candidates:  {len(golden['heading_candidates'])}")
    print(f"  post_body_titles:    {golden['post_body_titles']}")
    print(f"  toc_role_summary:    {golden['toc_role_summary']}")


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="Generate Biopolitics Phase 1 golden fixture")
    p.add_argument("--pdf", default="", help="Path to Biopolitics.pdf for pdf_font_band")
    args = p.parse_args()
    main(pdf_path=args.pdf)
